#!/usr/bin/env bash
# Build an AppImage for iced_lens so testers can run a single portable binary with the right assets.
# Default artifact path: target/release/iced_lens-<version>-<arch>.AppImage (override with --output-dir or APPIMAGE_OUTPUT_DIR).
#
# Dependencies bundled automatically by linuxdeploy:
# - FFmpeg libraries (libavcodec, libavformat, libavutil, libswscale, libswresample)
# - Audio libraries (libasound/ALSA, libpulse/PulseAudio)
# - Hardware acceleration libs (libva, libvdpau) when available
#
# File dialogs (rfd crate) use xdg-desktop-portal on modern Linux desktops.
#
# Note: The binary links dynamically to FFmpeg. linuxdeploy automatically bundles
# all shared library dependencies found via ldd. For systems without FFmpeg,
# the AppImage should work as long as the bundled libs are compatible.
set -euo pipefail

# Keep all intermediate artifacts under target/ to avoid dirtying the repo tree.
ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
TARGET_DIR="$ROOT_DIR/target"
BUILD_DIR="$TARGET_DIR/appimage"
APPDIR="$BUILD_DIR/AppDir"
BIN_NAME="iced_lens"
LINUXDEPLOY_BIN=${LINUXDEPLOY_BIN:-${LINUXDEPLOY:-linuxdeploy}}
# Default AppImage output goes under target/release so CI artifacts stay with cargo builds.
OUTPUT_DIR=${APPIMAGE_OUTPUT_DIR:-$TARGET_DIR/release}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --linuxdeploy|--linuxdeploy-bin)
      LINUXDEPLOY_BIN="$2"
      shift 2
      ;;
    --output-dir)
      OUTPUT_DIR="$2"
      shift 2
      ;;
    --help|-h)
      cat <<'USAGE'
Usage: scripts/build-appimage.sh [--linuxdeploy <path>] [--output-dir <dir>]

Environment overrides:
  LINUXDEPLOY_BIN       Path to linuxdeploy binary (preferred)
  LINUXDEPLOY           Legacy env alias for linuxdeploy path
  APPIMAGE_OUTPUT_DIR   Destination directory for final AppImage (default target/release)

Bundled dependencies (via linuxdeploy):
  - FFmpeg libraries (libavcodec, libavformat, libavutil, libswscale, libswresample)
  - Audio libraries (libasound/ALSA, libpulse/PulseAudio via cpal)
  - Hardware acceleration (libva, libvdpau when available)

Build requirements:
  - FFmpeg development headers (libavcodec-dev, libavformat-dev, etc.)
  - ALSA development headers (libasound2-dev)
  - linuxdeploy (https://github.com/linuxdeploy/linuxdeploy)

Note: The script automatically detects the host architecture (x86_64, aarch64, etc.).
      For ARM64 builds, run this script on an ARM64 machine with dependencies installed.
      File dialogs use xdg-desktop-portal on modern systems (no GTK bundling needed).
USAGE
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 2
      ;;
  esac
done

if ! command -v cargo >/dev/null 2>&1; then
  echo "cargo is required but not found in PATH" >&2
  exit 1
fi

if ! command -v "$LINUXDEPLOY_BIN" >/dev/null 2>&1; then
  echo "linuxdeploy not found. Set the LINUXDEPLOY env var to its path." >&2
  exit 1
fi

# Use the Cargo version to guarantee the AppImage filename matches published builds.
VERSION=$(awk -F '"' '/^version = "[0-9]+\./ {print $2; exit}' "$ROOT_DIR/Cargo.toml")
if [[ -z "$VERSION" ]]; then
  VERSION="dev"
fi

ARCH="$(uname -m)"
OUTPUT_NAME="${BIN_NAME}-${VERSION}-${ARCH}.AppImage"
OUTPUT_PATH="$OUTPUT_DIR/$OUTPUT_NAME"

# Release build ensures optimized binary is packaged just like production releases.
cargo build --release

BIN_PATH="$TARGET_DIR/release/$BIN_NAME"

if [[ ! -x "$BIN_PATH" ]]; then
  echo "Built binary not found at $BIN_PATH" >&2
  exit 1
fi

rm -rf "$BUILD_DIR"
mkdir -p "$APPDIR/usr/bin" \
         "$APPDIR/usr/share/$BIN_NAME/assets" \
         "$APPDIR/usr/share/icons/hicolor/scalable/apps" \
         "$APPDIR/usr/share/applications"

install -m 755 "$BIN_PATH" "$APPDIR/usr/bin/$BIN_NAME"

# Ship translations with the bundle because users may launch the AppImage offline.
I18N_SRC="$ROOT_DIR/assets/i18n"
I18N_DEST="$APPDIR/usr/share/$BIN_NAME/assets/i18n"
if [[ ! -d "$I18N_SRC" ]]; then
  echo "Missing translations directory: $I18N_SRC" >&2
  exit 1
fi
mkdir -p "$I18N_DEST"
cp -a "$I18N_SRC/." "$I18N_DEST/"

# Desktop environments discover the app icon through the standard hicolor path.
# Icons are generated by build.rs from the master SVG in assets/branding/iced_lens.svg.
# Generated icons are in target/branding/ after cargo build.
BRANDING_DIR="$TARGET_DIR/branding"
if [[ ! -d "$BRANDING_DIR" ]]; then
  echo "Branding directory not found: $BRANDING_DIR" >&2
  echo "Icons are generated during 'cargo build'. Ensure build completed successfully." >&2
  exit 1
fi

# Install scalable SVG (source of truth)
ICON_SVG_SRC="$ROOT_DIR/assets/branding/iced_lens.svg"
ICON_DEST="$APPDIR/usr/share/icons/hicolor/scalable/apps/iced_lens.svg"
install -m 644 "$ICON_SVG_SRC" "$ICON_DEST"

# Install generated PNG icons for better desktop integration
for size in 64 128 256; do
  PNG_SRC="$BRANDING_DIR/iced_lens-${size}.png"
  PNG_DEST="$APPDIR/usr/share/icons/hicolor/${size}x${size}/apps/iced_lens.png"
  if [[ -f "$PNG_SRC" ]]; then
    mkdir -p "$(dirname "$PNG_DEST")"
    install -m 644 "$PNG_SRC" "$PNG_DEST"
  fi
done

# Copy custom icon license where linuxdeploy expects dpkg-style copyright info.
DOC_DIR="$APPDIR/usr/share/doc/$BIN_NAME"
mkdir -p "$DOC_DIR"
if [[ -f "$ROOT_DIR/ICON_LICENSE.md" ]]; then
  cp "$ROOT_DIR/ICON_LICENSE.md" "$DOC_DIR/copyright"
fi

DESKTOP_FILE="$APPDIR/usr/share/applications/iced_lens.desktop"
# Provide a .desktop file so the AppImage integrates with menus when registered.
cat >"$DESKTOP_FILE" <<'EOF'
[Desktop Entry]
Type=Application
Name=Iced Lens
Comment=Privacy-first media viewer and editor with AI enhancement
Exec=iced_lens %F
Icon=iced_lens
Categories=Graphics;Viewer;Video;AudioVideo;
MimeType=image/jpeg;image/png;image/gif;image/webp;image/bmp;image/svg+xml;video/mp4;video/x-msvideo;video/quicktime;video/x-matroska;video/webm;
Terminal=false
EOF

# Custom AppRun injects --i18n-dir so the binary loads bundled translations instead of host files.
APPRUN="$APPDIR/AppRun"
cat >"$APPRUN" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
APPDIR=$(cd "$(dirname "$0")" && pwd)
I18N_DIR=${ICED_LENS_I18N_DIR:-"$APPDIR/usr/share/iced_lens/assets/i18n"}
exec "$APPDIR/usr/bin/iced_lens" --i18n-dir "$I18N_DIR" "$@"
EOF
chmod +x "$APPRUN"

# Run linuxdeploy inside the build dir so its output lands next to AppDir for easy cleanup.
pushd "$BUILD_DIR" >/dev/null
export ARCH # AppImage tooling reads ARCH to label metadata correctly.

"$LINUXDEPLOY_BIN" --appdir "$APPDIR" \
  --desktop-file "$DESKTOP_FILE" \
  --icon-file "$ICON_DEST" \
  --output appimage
NEW_APPIMAGE=$(find "$BUILD_DIR" -maxdepth 1 -type f -name "*.AppImage" -print -quit)
popd >/dev/null

if [[ -z "$NEW_APPIMAGE" ]]; then
  echo "linuxdeploy did not produce an AppImage" >&2
  exit 1
fi

mkdir -p "$OUTPUT_DIR"
mv "$NEW_APPIMAGE" "$OUTPUT_PATH"
echo "AppImage created at $OUTPUT_PATH"

# Verify critical FFmpeg and audio libraries are bundled
echo "Verifying bundled libraries..."
MISSING_LIBS=()
for lib in libavcodec libavformat libavutil libswscale libswresample libasound; do
  if ! find "$APPDIR" -name "${lib}.so*" -print -quit | grep -q .; then
    MISSING_LIBS+=("$lib")
  fi
done

if [[ ${#MISSING_LIBS[@]} -gt 0 ]]; then
  echo "Warning: The following libraries may not be bundled: ${MISSING_LIBS[*]}" >&2
  echo "The AppImage may not work on systems without these libraries installed." >&2
else
  echo "All critical libraries (FFmpeg, ALSA) are bundled."
fi

# Generate SHA256 checksum for integrity verification
CHECKSUM_FILE="${OUTPUT_PATH}.sha256"
if command -v sha256sum >/dev/null 2>&1; then
  (cd "$OUTPUT_DIR" && sha256sum "$(basename "$OUTPUT_PATH")") > "$CHECKSUM_FILE"
  echo "SHA256 checksum: $CHECKSUM_FILE"
elif command -v shasum >/dev/null 2>&1; then
  # macOS fallback
  (cd "$OUTPUT_DIR" && shasum -a 256 "$(basename "$OUTPUT_PATH")") > "$CHECKSUM_FILE"
  echo "SHA256 checksum: $CHECKSUM_FILE"
else
  echo "Warning: sha256sum not found, checksum file not generated" >&2
fi
